export const TICKET_CONSTANTS = {
  TICKET_LIST_REQUEST: "TICKET_LIST_REQUEST",
  TICKET_LIST_SUCCESS: "TICKET_LIST_SUCCESS",
  TICKET_LIST_FAILURE: "TICKET_LIST_FAILURE",

  TICKET_CREATE_REQUEST: "TICKET_CREATE_REQUEST",
  TICKET_CREATE_SUCCESS: "TICKET_CREATE_SUCCESS",
  TICKET_CREATE_FAILURE: "TICKET_CREATE_FAILURE",
};
