# Generated by Django 2.2.24 on 2021-11-07 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211105_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Proyecto'),
        ),
    ]
